export enum HubEventEnum {
  ConnectUserToGame = 'ConnectUserToGame',
  JoinToGame = 'JoinToGame',
  GetStartTime = 'GetStartTime',
  GetGameProcess = 'GetGameProcess',
  GetGameState = 'GetGameState',
  StartGame = 'StartGame',
  Error = 'Error',
  FirstRoundSelectQuestion = 'FirstRoundSelectQuestion',
  FirstRoundReceivingAnswers = 'FirstRoundReceivingAnswers',
  SecondRoundSelectQuestion = 'SecondRoundSelectQuestion',
  SecondRoundReceivingAnswers = 'SecondRoundReceivingAnswers',
  SendChatMessage = 'SendChatMessage',
  UserJoinGame = 'UserJoinGame',
  ThirdRoundSelectQuestion = 'ThirdRoundSelectQuestion',
  ThirdRoundReceivingAnswers = 'ThirdRoundReceivingAnswers',
}
